FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy application files
COPY backend ./backend
COPY scripts ./scripts

WORKDIR /app/backend

EXPOSE 3000

CMD ["node", "app.js"]
